<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Букеты</title>';
echo '<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"';
echo 'integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="';
echo 'crossorigin=""/>';
echo '<link href="style/style.css" rel="stylesheet"/>';
echo '</head>';
echo '';
echo '<body class="body">';
echo '<header>';
echo '<div class="container">';
echo '<div class="header__logo">';
echo '<div class="header__text">';
echo 'Flowers';
echo '</div>';
echo '</div>';
echo '<ul class="header__list">';
echo '<li><a href="#about" class="header__item">О нас</a></li>';
echo '<li><a href="#bouquets" class="header__item">Букеты</a></li>';
echo '<li><a href="#reviews" class="header__item">Отзывы</a></li>';
echo '<li><a href="#payment" class="header__item">Доставка и оплата</a></li>';
echo '<li><a href="#contacts" class="header__item">Контакты</a></li>';
echo '</ul>';
echo '<div class="header__menu" data-set="closed"></div>';
echo '<div class="drop hide">';
echo '<div class="bg" data-set="bg"></div>';
echo '<div class="close" data-set="close">×</div>';
echo '<ul>';
echo '<li><a href="#about" class="header__item">О нас</a></li>';
echo '<li><a href="#bouquets" class="header__item">Букеты</a></li>';
echo '<li><a href="#reviews" class="header__item">Отзывы</a></li>';
echo '<li><a href="#payment" class="header__item">Доставка и оплата</a></li>';
echo '<li><a href="#contacts" class="header__item">Контакты</a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</header>';
echo '<main>';
echo '<div class="no-padding-media container">';
echo '<div class="main__offer">';
echo '<div class="offer__title">';
echo 'Быстрая доставка букетов по всему Минску';
echo '</div>';
echo '<div class="offer__show">';
echo '<a href="#bouquets" class="offer__btn btn">';
echo 'Выбрать букеты';
echo '</a>';
echo '</div>';
echo '</div>';
echo '<div id="about" class="about">';
echo '<div class="about__title title">О нас</div>';
echo '<div class="about__list">';
echo '<div class="about__item">';
echo '<div class="item__img img__style">';
echo '<img src="img/first.svg">';
echo '</div>';
echo '<div class="item__text">';
echo 'Демократичные цены';
echo '</div>';
echo '</div>';
echo '<div class="about__item">';
echo '<div class="item__img">';
echo '<img src="img/second.svg">';
echo '</div>';
echo '<div class="item__text">';
echo 'Самые стильные букеты';
echo '</div>';
echo '</div>';
echo '<div class="about__item">';
echo '<div class="item__img">';
echo '<img src="img/three.svg">';
echo '</div>';
echo '<div class="item__text">';
echo 'Самые свежиеe цветы';
echo '</div>';
echo '</div>';
echo '<div class="about__item">';
echo '<div class="complex__img">';
echo '<img class="complex__first" src="img/four1.svg">';
echo '<img class="complex__second" src="img/four2.svg">';
echo '</div>';
echo '<div class="item__text">';
echo 'Быстрая доставка';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="bouquets" class="bouquets">';
echo '<div class="bouquets__title title">Букеты</div>';
echo '<div class="bouquets__choice">';
echo '<div class="bouquets__item">';
echo '<div class="bouquets__item-img">';
echo '<img data-show="full" src="img/bouquet1.png">';
echo '</div>';
echo '<div class="bouquets__item-name">';
echo 'Букет "Нежность"';
echo '</div>';
echo '<div class="bouquets__item-price">';
echo '<span>100</span>BYN';
echo '</div>';
echo '<div class="bouquets__item-order">';
echo '<a href="#form" class="btn">Заказать</a>';
echo '</div>';
echo '</div>';
echo '<div class="bouquets__item">';
echo '<div class="bouquets__item-img">';
echo '<img data-show="full" src="img/bouquet2.png">';
echo '</div>';
echo '<div class="bouquets__item-name">';
echo 'Букет "Ласка"';
echo '</div>';
echo '<div class="bouquets__item-price">';
echo '<span>150</span>BYN';
echo '</div>';
echo '<div class="bouquets__item-order">';
echo '<a href="#form" class="btn">Заказать</a>';
echo '</div>';
echo '</div>';
echo '<div class="bouquets__item">';
echo '<div class="bouquets__item-img">';
echo '<img data-show="full" src="img/bouquet3.png">';
echo '</div>';
echo '<div class="bouquets__item-name">';
echo 'Букет "Любовь"';
echo '</div>';
echo '<div class="bouquets__item-price">';
echo '<span>200</span>BYN';
echo '</div>';
echo '<div class="bouquets__item-order">';
echo '<a href="#form" class="btn">Заказать</a>';
echo '</div>';
echo '</div>';
echo '<div class="bouquets__item">';
echo '<div class="bouquets__item-img">';
echo '<img data-show="full" src="img/bouquet4.png">';
echo '</div>';
echo '<div class="bouquets__item-name">';
echo 'Букет "Оригинальный"';
echo '</div>';
echo '<div class="bouquets__item-price">';
echo '<span>200</span>BYN';
echo '</div>';
echo '<div class="bouquets__item-order">';
echo '<a href="#form" class="btn">Заказать</a>';
echo '</div>';
echo '</div>';
echo '<div class="bouquets__item">';
echo '<div class="bouquets__item-img">';
echo '<img data-show="full" src="img/bouquet5.png">';
echo '</div>';
echo '<div class="bouquets__item-name">';
echo 'Букет "Улыбка"';
echo '</div>';
echo '<div class="bouquets__item-price">';
echo '<span>200</span>BYN';
echo '</div>';
echo '<div class="bouquets__item-order">';
echo '<a href="#form" class="btn">Заказать</a>';
echo '</div>';
echo '</div>';
echo '<div class="bouquets__item">';
echo '<div class="bouquets__item-img">';
echo '<img data-show="full" src="img/bouquet6.png">';
echo '</div>';
echo '<div class="bouquets__item-name">';
echo 'Букет "Поцелуй"';
echo '</div>';
echo '<div class="bouquets__item-price">';
echo '<span>200</span>BYN';
echo '</div>';
echo '<div class="bouquets__item-order">';
echo '<a href="#form" class="btn">Заказать</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="payment" class="about__payment">';
echo '<div class="payment__title-top title">Оплата и доставка</div>';
echo '<div class="payment__list">';
echo '<div class="payment__item">';
echo '<div class="payment__img">';
echo '<img src="img/first.svg">';
echo '</div>';
echo '<div class="payment__title">Оплата</div>';
echo '<div class="payment__descr">Оплатить заказ можно при получении либо в пункте самовывоза</div>';
echo '</div>';
echo '<div class="payment__item">';
echo '<div class="payment__complex-img">';
echo '<img class="complex__first" src="img/four1.svg">';
echo '<img class="complex__second" src="img/four2.svg">';
echo '</div>';
echo '<div class="payment__title">Доставка</div>';
echo '<div class="payment__descr">Доставим в любую точку Минска в течение дня</div>';
echo '</div>';
echo '<div class="payment__item">';
echo '<div class="payment__img">';
echo '<img src="img/three.svg">';
echo '</div>';
echo '<div class="payment__title">Самовывоз</div>';
echo '<div class="payment__descr">Вы можете забрать букет самостоятельно по адресу г. Минск, ул. Белая 1';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="reviews" class="reviews">';
echo '<div class="reviews__title title">';
echo 'Отзывы';
echo '</div>';
echo '<div class="reviews__slider">';
echo '<div class="reviews__left">';
echo '<img src="icons/left.svg">';
echo '</div>';
echo '<div class="reviews__main">';
echo '<div class="reviews__tape">';
echo '<div class="reviews__item">';
echo '<div class="reviews__item-info">';
echo '<div class="reviews__item-photo">';
echo '<img src="img/photo.png">';
echo '</div>';
echo '<div class="reviews__item-name">Анастасия Иванова </div>';
echo '<div class="reviews__item-text">';
echo 'Спасибо за чудесный букет! Все пришло вовремя)';
echo '</div>';
echo '</div>';
echo '<div class="reviews__bouquetphoto">';
echo '<img data-show="full" src="img/review1.png">';
echo '</div>';
echo '</div>';
echo '<div class="reviews__item">';
echo '<div class="reviews__item-info">';
echo '<div class="reviews__item-photo">';
echo '<img data-show="full" src="img/photo.png">';
echo '</div>';
echo '<div class="reviews__item-name">Анастасия Иванова </div>';
echo '<div class="reviews__item-text">';
echo 'Спасибо за чудесный букет! Все пришло вовремя)';
echo '</div>';
echo '</div>';
echo '<div class="reviews__bouquetphoto">';
echo '<img data-show="full" src="img/bouquet4.png">';
echo '</div>';
echo '</div>';
echo '<div class="reviews__item">';
echo '<div class="reviews__item-info">';
echo '<div class="reviews__item-photo">';
echo '<img src="img/photo.png">';
echo '</div>';
echo '<div class="reviews__item-name">Анастасия Иванова </div>';
echo '<div class="reviews__item-text">';
echo 'Спасибо за чудесный букет! Все пришло вовремя)';
echo '</div>';
echo '</div>';
echo '<div class="reviews__bouquetphoto">';
echo '<img data-show="full" src="img/bouquet3.png">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="reviews__right">';
echo '<img src="icons/right.svg">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="form" class="formfield">';
echo '<div class="container">';
echo '<div class="formfield__title title">Оформить заказ</div>';
echo '<div class="formfield__main">';
echo '<form method="#" class="main">';
echo '<div id="initials" class="formfield__fullinput">';
echo '<input id="name" type="text" name="name" placeholder="Имя*" required>';
echo '<input id="lastname" type="text" name="lastname" placeholder="Фамилия*" required>';
echo '<input id="mobile" type="number" name="mobile" placeholder="Телефон*" required>';
echo '</div>';
echo '<div class="formfield__aim">';
echo '<div class="formfield__aim-title title">Букет*</div>';
echo '<div class="formfield__aim-items">';
echo '<div class="aim__item">';
echo '<input type="checkbox" class="checkbox" name="aim" id="tenderness">';
echo '<label for="tenderness"></label>';
echo '<label for="tenderness" type="hidden"><p>Нежность <span>100 BYN</span></p></label>';
echo '</div>';
echo '<div class="aim__item">';
echo '<input type="checkbox" class="checkbox" name="aim" id="kidness">';
echo '<label for="kidness"></label>';
echo '<label for="kidness" type="hidden"><p>Ласка <span>150 BYN</span></p></label>';
echo '</div>';
echo '<div class="aim__item">';
echo '<input type="checkbox" class="checkbox" name="aim" id="love">';
echo '<label for="love"></label>';
echo '<label for="love" type="hidden"><p>Любовь <span>200 BYN</span></p></label>';
echo '</div>';
echo '<div class="aim__item">';
echo '<input type="checkbox" class="checkbox" name="aim" id="original">';
echo '<label for="original"></label>';
echo '<label for="original" type="hidden"><p>Оригинальный <span>120 BYN</span></p></label>';
echo '</div>';
echo '<div class="aim__item">';
echo '<input type="checkbox" class="checkbox" name="aim" id="smile">';
echo '<label for="smile"></label>';
echo '<label for="smile" type="hidden"><p>Улыбка <span>140 BYN</span></p></label>';
echo '</div>';
echo '<div class="aim__item">';
echo '<input type="checkbox" class="checkbox" name="aim" id="kiss">';
echo '<label for="kiss"></label>';
echo '<label for="kiss" type="hidden"><p>Поцелуй <span>210 BYN</span></p></label>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="formfield__putin">';
echo '<div class="formfield__putin-title title">Букет оформить в*</div>';
echo '<div class="formfield__putin-boxes">';
echo '<div class="putin__box">';
echo '<input type="radio" class="radio" name="put" id="box">';
echo '<label for="box"></label>';
echo '<label for="box" type="hidden"><p>Коробку (+2 BYN)</p></label>';
echo '</div>';
echo '<div class="putin__box">';
echo '<input type="radio" class="radio" name="put" id="paper">';
echo '<label for="paper"></label>';
echo '<label for="paper" type="hidden"><p>Флористическую бумагу</p></label>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="formfield__delivery">';
echo '<div class="formfield__delivery-date">';
echo '<div class="formfield__delivery-title title">';
echo 'Дата доставки*';
echo '</div>';
echo '<div class="formfield__delivery-calendar">';
echo '<input type="text" value="Задать" name="calendar" id="calendar" data-set="settime" required readonly>';
echo '<div class="calendar__icon">';
echo '<img src="icons/calendar.svg">';
echo '</div>';
echo '</div>';
echo '<div class="calendar hide">';
echo '<div class="calendar__top">';
echo '<div class="calendar__left">';
echo '<img src="icons/left.svg">';
echo '</div>';
echo '<div class="calendar__month">Октябрь</div>';
echo '<div class="calendar__right">';
echo '<img src="icons/right.svg">';
echo '</div>';
echo '</div>';
echo '<ul class="calendar__days">';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="formfield__delivery-time">';
echo '<div class="formfield__delivery-title title">';
echo 'Время доставки*';
echo '</div>';
echo '<div class="formfield__delivery-clock">';
echo '<input type="text" value="Задать" name="clock" id="clock" data-set="settime" required';
echo 'readonly>';
echo '<div class="clock__icon">+</div>';
echo '</div>';
echo '<div class="clock hide">';
echo '<div class="clock__item"><span data-from>9:00</span data-to>-<span>12:00</span></div>';
echo '<div class="clock__item"><span data-from>12:00</span data-to>-<span>15:00</span></div>';
echo '<div class="clock__item"><span data-from>15:00</span data-to>-<span>18:00</span></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="formfield__address formfield__fullinput">';
echo '<input id="address" type="text" name="address" placeholder="Адрес доставки*" required>';
echo '</div>';
echo '<div class="formfield__comments">';
echo '<textarea name="comments" id="comments" placeholder="Комментарии к заказу"></textarea>';
echo '</div>';
echo '<div class="formfield__footnote">';
echo '* обязательно для заполнения';
echo '</div>';
echo '<div class="formfield__total">';
echo 'Итого: <span class="formfield__total-price">101</span> <span';
echo 'class="formfield__total-currency">BYN</span>';
echo '</div>';
echo '<div class="formfield__totalbuttons">';
echo '<div class="formfield__totalorder">';
echo '<button type="submit" class="btn" name="submit" href="#">Заказать</button>';
echo '</div>';
echo '<div class="formfield__totalclean">';
echo '<button type="reset" class="btn-reverse" name="reset" href="#">Очистить</button>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="contacts" class="no-padding-media leaf">';
echo '<div id="map"></div>';
echo '<aside>';
echo '<div class="aside__address">';
echo '<img src="icons/marker.svg">';
echo '<span>Минск, ул. Белая 1</span>';
echo '</div>';
echo '<div class="aside__phone">';
echo '<img src="icons/phone.svg">';
echo '<span>+375 (29) 123-45-67</span>';
echo '</div>';
echo '<div class="aside__icons">';
echo '<div><img src="icons/viber.svg"></div>';
echo '<div><img src="icons/telegram.svg"></div>';
echo '<div><img src="icons/whatsapp.svg"></div>';
echo '<div><img src="icons/instagram.svg"></div>';
echo '<div><img src="icons/facebook.svg"></div>';
echo '<div><img src="icons/vk.svg"></div>';
echo '</div>';
echo '<div class="aside__call">';
echo '<div class="aside__btn">Заказать звонок</div>';
echo '</div>';
echo '</aside>';
echo '<div class="to__top">';
echo '<img src="icons/Vector 3.svg">';
echo '</div>';
echo '<div class="popup hide">';
echo '<div class="popup__dialog">';
echo '<div class="popup__close">';
echo '<img src="icons/close.svg">';
echo '</div>';
echo '<div class="popup__title">';
echo 'Заказать звонок';
echo '</div>';
echo '<div class="popup__text">';
echo 'Оставьте свой номер телефона, и мы перезвоним Вам.';
echo '</div>';
echo '<div class="popup__form">';
echo '<form>';
echo '<input type="phone" name="phonePopup" id="phone-popup" required placeholder="Телефон*">';
echo '<button type="submit">Заказать звонок</button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</main>';
echo '<footer>';
echo '<div class="container">';
echo '<div class="footer__logo">';
echo '<div class="footer__text">';
echo 'Flowers';
echo '</div>';
echo '</div>';
echo '<ul class="footer__list">';
echo '<li><a href="#about" class="footer__item">О нас</a></li>';
echo '<li><a href="#bouquets" class="footer__item">Букеты</a></li>';
echo '<li><a href="#reviews" class="footer__item">Отзывы</a></li>';
echo '<li><a href="#payment" class="footer__item">Доставка и оплата</a></li>';
echo '<li><a href="#contacts" class="footer__item">Контакты</a></li>';
echo '<li><img src="icons/phone.svg">+375 (29) 123-45-67</li>';
echo '</ul>';
echo '</div>';
echo '</footer>';
echo '<script src="js/script.js"></script>';
echo '</body>';
echo '</html>';
?>
